services:
  - type: web
    name: prepai-backend
    env: node
    rootDir: Backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production